[server]
port = 18051
enableStaticServing = true
enableCORS = true
enableWebsocketCompression = true
enableXsrfProtection = true
baseUrlPath = ""  # 确保没有设置基础路径


[browser]
serverPort = 18051
serverAddress = "localhost"
gatherUsageStats = false


# 使用 jsDelivr + npm 包
[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-200-normal.woff2"
style = "normal"
weight = "200"

[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-300-normal.woff2"
style = "normal"
weight = "300"

[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-400-normal.woff2"
style = "normal"
weight = "400"

[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-500-normal.woff2"
style = "normal"
weight = "500"

[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-600-normal.woff2"
style = "normal"
weight = "600"

[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-700-normal.woff2"
style = "normal"
weight = "700"

[[theme.fontFaces]]
family = "Noto Serif SC"
url = "https://cdn.jsdelivr.net/npm/@fontsource/noto-serif-sc@5.0.0/files/noto-serif-sc-chinese-simplified-900-normal.woff2"
style = "normal"
weight = "900"

[theme]
font = "Noto Serif SC"
base = "dark"
primaryColor = "#1ed760"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
textColor = "#ffffff"
linkColor = "#1ed760"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "full"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2.5rem", "2.25rem", "2rem", "1.5rem"]
chartCategoricalColors = ["#ffc862", "#2d46b9", "#b49bc8"]

[theme.sidebar]
backgroundColor = "#121212"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#696969"